Dat257 57 Update database with more data
filipkauffeldt/DAT257-group-8 pull request #28
Opened 2024-05-07 11:17 UTC by filipkauffeldt

Add more data for most countries to the database and fix bugs with country repository and csv reader

2024-05-08 09:32 UTC, jakobschy commented on API/Model/CountryRepository.cs
> +        public async Task<Country> AddCountryAsync(Country country)
Looks like the CountryController is still using the AddCountry Function

2024-05-08 09:40 UTC, jakobschy requested changes
Branch produces errors when run

2024-05-08 10:46 UTC, filipkauffeldt commented
> Branch produces errors when run

Fixed

2024-05-08 12:45 UTC, jakobschy approved these changes, later dismissed
Looks good

2024-05-09 10:14 UTC, jakobschy approved these changes

2024-05-09 10:17 UTC, merged